# Base Image for Spark Operator using Go 1.19
FROM golang:1.19 as builder

#Set necessary environment variables
ENV OPERATOR_VERSION v1beta2-1.3.8-3.1.1
#ENV OPERATOR_VERSION v1beta2-1.3.8-3.2.0
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=s390x

# Install necessary dependencies
RUN apt-get update && apt-get install -y git make gcc

# Set working directory inside container
WORKDIR /workspace

# Clone the Spark Operator repository from GoogleCloudPlatform GitHub
RUN git clone https://github.com/GoogleCloudPlatform/spark-on-k8s-operator.git /workspace/spark-on-k8s-operator

# Checkout the specific version
RUN cd /workspace/spark-on-k8s-operator && git checkout ${OPERATOR_VERSION}

# Ensure all Go dependencies are downloaded
RUN cd /workspace/spark-on-k8s-operator && go mod tidy && go mod vendor

# Build the Spark Operator binary from the main.go file in the root directory
RUN cd /workspace/spark-on-k8s-operator && go build -o spark-operator main.go

# Final image: Switch from distroless to a minimal Debian-based image
#FROM debian:bullseye-slim
FROM quay.io/tonyfieit75/spark-3.2.0:s390x-4

# Install basic utilities for debugging
RUN apt-get update && apt-get install -y \
    bash \
    tar \
    coreutils \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Set the environment variables to propagate the correct paths for spark-submit
ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$PATH

# Set working directory for runtime container
WORKDIR /

# Copy the Spark Operator binary from the builder container
COPY --from=builder /workspace/spark-on-k8s-operator/spark-operator /usr/local/bin/spark-operator

# Expose the Spark Operator's default port
EXPOSE 8080

# Set the entry point for the container
ENTRYPOINT ["/usr/local/bin/spark-operator"]

