apiVersion: v1
kind: Service
metadata:
  name: spark-operator-webhook-svc
  namespace: default
spec:
  ports:
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: https-webhook
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/component: webhook


