apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-webhook
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources:
      - sparkapplications
      - scheduledsparkapplications
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get", "list", "watch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-webhook-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-operator-webhook
subjects:
  - kind: ServiceAccount
    name: spark-operator-webhook
    namespace: default

