apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-extended-clusterrole
rules:
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets", "pushsecrets", "clusterexternalsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["namespaces", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

