apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: default
spec:
  backendType: vault
  data:
    - key: secret/data/my-secret
      name: my-key
      property: my-key
  vaultMountPoint: ""

