apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: external-secrets-operator
  namespace: default
spec:
  serviceName: "external-secrets-operator"
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets-operator
  template:
    metadata:
      labels:
        app: external-secrets-operator
    spec:
      serviceAccountName: external-secrets-sa
      containers:
      - name: external-secrets-operator
        image: quay.io/tonyfieit75/external-secrets-operator:s390x-1
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VAULT_ADDR
          value: "http://vault-service.default:8200"
        - name: VAULT_TOKEN
          value: "root"  # In production, you'd use a secret
        - name: OPERATOR_NAME
          value: "external-secrets-operator"

